---
substitutions:
  # App Version
  app_version: "26.6.6"
  # github URL
  github_url: "https://github.com/TheRealFalseReality/Aquaponics_Pool_Kit-AtlasScientific"

  sorting_group_name: "AquaPi"
  update_pmp_green: "never"
  update_pmp_red: "never"
  
  wq_temp_sensor_id: rtd_ezo
  wq_ideal_temp_id: ideal_temp_rtd

text_sensor:
  # AquaPi Version
  - id: !extend app_version
    name: "AquaPi Kits Version"

switch:
  - platform: gpio
    id: en_rtd
    name: "RTD Enable"
    pin: GPIO9
    internal: true
    restore_mode: ALWAYS_ON
    entity_category: config

esphome:
  on_boot:
    priority: 800
    then:
      - switch.turn_on: en_rtd
      - button.press: read_ph
      - button.press: read_rtd
      - button.press: read_do
      - button.press: read_ec

select:
  - platform: template
    name: "Temperature Display Unit"
    id: temp_display_unit
    icon: mdi:temperature-celsius
    options:
      - "Celsius"
      - "Fahrenheit"
    initial_option: "Fahrenheit"
    optimistic: true
    restore_value: true
    entity_category: "Config"
    on_value:
      then:
        - component.update: tft_display

sensor:
  - platform: template
    name: "Temperature EZO °F"
    id: rtd_temp_f
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    internal: true
    device_class: temperature
    state_class: measurement
    update_interval: "${update_rtd}"
    lambda: |-
      if (!id(rtd_ezo).has_state()) return NAN;
      return (id(rtd_ezo).state * 9.0f / 5.0f) + 32.0f;
    web_server:
      sorting_group_id: sorting_group_rtd
      sorting_weight: 11